---

- name: Fail if required postgres-backup-s3 settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'postgres_backup_s3_bucket', when: true}
    - {'name': 'postgres_backup_s3_database', when: true}
    - {'name': 'postgres_backup_s3_host', when: true}
    - {'name': 'postgres_backup_s3_user', when: true}
    - {'name': 'postgres_backup_s3_password', when: true}
